# SPDX-License-Identifier: AGPL-3.0-or-later
# QUASI Cargo workspace — all Rust crates live here.

[workspace]
members = [
    "afana",
    "quasi-bridge",
    "quasi-cache",
    "quasi-cudaq-ffi",
    "quasi-demo",
    "quasi-scheduler",
    "quasi-senate",
    "quasi-solvayeur",
]
resolver = "2"

[workspace.dependencies]
hal-contract = { path = "../hal-contract/rust" }
