version: '3.8'

services:
  quasi-board:
    build:
      context: .
      dockerfile: quasi-board/Dockerfile
    ports:
      - "8420:8420"
    volumes:
      - quasi-ledger:/home/vops/quasi-ledger

volumes:
  quasi-ledger:
