#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright 2026 QUASI Contributors
"""
generate_gate_issues.py — Batch-create tier-1 GitHub issues for missing gates.

Each issue adds a single gate to the GateName enum in afana/src/ast.rs,
including the four match arms (from_token, as_str, arity, is_parametric).

Usage:
    python3 quasi-senate/scripts/generate_gate_issues.py --dry-run
    python3 quasi-senate/scripts/generate_gate_issues.py
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
import urllib.error

GITHUB_REPO = "ehrenfest-quantum/quasi"
GITHUB_API = f"https://api.github.com/repos/{GITHUB_REPO}/issues"

# Gates to add — standard OpenQASM gates missing from the current 15-gate set.
# Each entry: (enum_variant, token, aliases, arity, is_parametric)
MISSING_GATES = [
    ("Ecr",  "ecr",  [],           2, False),
    ("Iswap", "iswap", [],         2, False),
    ("Sxdg", "sxdg", [],           1, False),
    ("Csx",  "csx",  [],           2, False),
    ("U1",   "u1",   [],           1, True),
    ("U2",   "u2",   [],           1, True),
    ("U3",   "u3",   [],           1, True),
    ("P",    "p",    ["phase"],    1, True),
    ("Id",   "id",   ["i"],        1, False),
]

# Verbatim code context from afana/src/ast.rs — the GateName enum and match arms
# that the solver needs to see to produce correct find/replace edits.
CODE_CONTEXT = r'''```rust
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum GateName {
    H,
    X,
    Y,
    Z,
    S,
    T,
    Sdg,
    Tdg,
    Cx,
    Cz,
    Swap,
    Ccx,
    Rx,
    Ry,
    Rz,
}

impl GateName {
    pub fn from_token(tok: &str) -> Option<Self> {
        match tok {
            "h" => Some(Self::H),
            "x" => Some(Self::X),
            // ... (remaining arms)
            "rz" => Some(Self::Rz),
            _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::H => "h",
            // ... (remaining arms)
            Self::Rz => "rz",
        }
    }

    pub fn arity(&self) -> usize {
        match self {
            Self::H | Self::X | Self::Y | Self::Z => 1,
            Self::S | Self::T | Self::Sdg | Self::Tdg => 1,
            Self::Rx | Self::Ry | Self::Rz => 1,
            Self::Cx | Self::Cz | Self::Swap => 2,
            Self::Ccx => 3,
        }
    }

    pub fn is_parametric(&self) -> bool {
        matches!(self, Self::Rx | Self::Ry | Self::Rz)
    }
}
```'''


def build_issue(variant: str, token: str, aliases: list[str],
                arity: int, parametric: bool) -> dict:
    alias_note = ""
    if aliases:
        alias_str = ", ".join(f'`"{a}"`' for a in aliases)
        alias_note = f" Also accept alias(es) {alias_str} in `from_token()`."

    param_note = "parametric (takes rotation parameter(s))" if parametric else "non-parametric"

    description = (
        f"The `{token}` gate is a standard OpenQASM 3 gate that is missing from "
        f"Afana's `GateName` enum. It is a {arity}-qubit {param_note} gate.{alias_note}\n\n"
        f"Add `GateName::{variant}` to the enum and update all four match arms in the "
        f"`impl GateName` block: `from_token()`, `as_str()`, `arity()`, and `is_parametric()`.\n\n"
        f"## Code context\n\n{CODE_CONTEXT}"
    )

    acceptance = [
        f"`cargo test` passes in `afana/`",
        f"`GateName::from_token(\"{token}\")` returns `Some(GateName::{variant})`",
        f"`GateName::{variant}.as_str()` returns `\"{token}\"`",
        f"`GateName::{variant}.arity()` returns `{arity}`",
    ]

    return {
        "title": f"Add GateName::{variant} to Afana gate set",
        "description": description,
        "acceptance_criteria": acceptance,
        "label": "compiler",
        "tier": 1,
    }


def open_github_issue(issue: dict, token: str) -> str:
    criteria_md = "\n".join(f"- [ ] {c}" for c in issue["acceptance_criteria"])
    body = (
        f"{issue['description']}\n\n"
        f"## Acceptance criteria\n\n{criteria_md}\n\n"
        f"---\n"
        f"*Generated by generate_gate_issues.py (batch tier-1 gate issues)*\n"
        f"Tier: {issue['tier']}"
    )
    payload = json.dumps({
        "title": issue["title"],
        "body": body,
        "labels": [issue["label"]],
    }).encode()
    req = urllib.request.Request(
        GITHUB_API, data=payload, method="POST",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read())
        return data["html_url"]


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate tier-1 gate issues")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print issues without creating them on GitHub")
    parser.add_argument("--gates", nargs="*", default=None,
                        help="Only generate for these gate variants (default: all)")
    args = parser.parse_args()

    github_token = os.environ.get("GITHUB_TOKEN", "").strip()
    if not args.dry_run and not github_token:
        print("Error: GITHUB_TOKEN required (or use --dry-run)", file=sys.stderr)
        sys.exit(1)

    gates = MISSING_GATES
    if args.gates:
        gate_set = set(g.lower() for g in args.gates)
        gates = [g for g in gates if g[0].lower() in gate_set or g[1] in gate_set]

    print(f"Generating {len(gates)} gate issue(s)...\n")

    for variant, token, aliases, arity, parametric in gates:
        issue = build_issue(variant, token, aliases, arity, parametric)
        print(f"  {issue['title']}")

        if args.dry_run:
            print(f"    Label: {issue['label']}, Tier: {issue['tier']}")
            print(f"    Criteria: {len(issue['acceptance_criteria'])} items")
            continue

        try:
            url = open_github_issue(issue, github_token)
            print(f"    -> {url}")
        except Exception as e:
            print(f"    ERROR: {e}", file=sys.stderr)

    print(f"\nDone. {'(dry run)' if args.dry_run else ''}")


if __name__ == "__main__":
    main()
