// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2026 QUASI Contributors
//! Typed AST for Ehrenfest programs.
//!
//! Produced by the Trotterization pass (`trotter.rs`) from the physics-level
//! `EhrenfestProgram` (deserialized from CBOR by `cbor.rs`). The AST is the
//! circuit-level representation consumed by the QASM emitter and ZX optimizer.

use serde::{Deserialize, Serialize};

// ── Gate names ───────────────────────────────────────────────────────────────

/// The set of gates Afana recognises.
///
/// Stored as lower-case canonical names. Aliases (`cnot` → `cx`,
/// `toffoli` → `ccx`) are resolved at parse time.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum GateName {
    H,
    X,
    Y,
    Z,
    S,
    T,
    Sdg,
    Tdg,
    Cx,
    Cz,
    Swap,
    Ccx,
    Rx,
    Ry,
    Rz,
}

impl GateName {
    /// Parse a gate name from a lower-cased token.
    ///
    /// Returns `None` for unrecognised tokens.
    pub fn from_token(tok: &str) -> Option<Self> {
        match tok {
            "h" => Some(Self::H),
            "x" => Some(Self::X),
            "y" => Some(Self::Y),
            "z" => Some(Self::Z),
            "s" => Some(Self::S),
            "t" => Some(Self::T),
            "sdg" => Some(Self::Sdg),
            "tdg" => Some(Self::Tdg),
            "cx" | "cnot" => Some(Self::Cx),
            "cz" => Some(Self::Cz),
            "swap" => Some(Self::Swap),
            "ccx" | "toffoli" => Some(Self::Ccx),
            "rx" => Some(Self::Rx),
            "ry" => Some(Self::Ry),
            "rz" => Some(Self::Rz),
            _ => None,
        }
    }

    /// Canonical lower-case QASM name.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::H => "h",
            Self::X => "x",
            Self::Y => "y",
            Self::Z => "z",
            Self::S => "s",
            Self::T => "t",
            Self::Sdg => "sdg",
            Self::Tdg => "tdg",
            Self::Cx => "cx",
            Self::Cz => "cz",
            Self::Swap => "swap",
            Self::Ccx => "ccx",
            Self::Rx => "rx",
            Self::Ry => "ry",
            Self::Rz => "rz",
        }
    }

    /// Number of qubit operands this gate requires.
    pub fn arity(&self) -> usize {
        match self {
            Self::H | Self::X | Self::Y | Self::Z => 1,
            Self::S | Self::T | Self::Sdg | Self::Tdg => 1,
            Self::Rx | Self::Ry | Self::Rz => 1,
            Self::Cx | Self::Cz | Self::Swap => 2,
            Self::Ccx => 3,
        }
    }

    /// Whether this gate takes a rotation parameter.
    pub fn is_parametric(&self) -> bool {
        matches!(self, Self::Rx | Self::Ry | Self::Rz)
    }

    /// Whether this gate is a Clifford gate.
    ///
    /// The Clifford group consists of gates generated by {H, S, CX}.
    /// Clifford gates: H, X, Y, Z, S, Sdg, CX, CZ, SWAP.
    /// Non-Clifford gates: T, Tdg, CCX (Toffoli), and Rx/Ry/Rz at
    /// non-Clifford angles.
    ///
    /// For parametric gates (Rx, Ry, Rz), this returns `false` since
    /// the Clifford-ness depends on the angle. Use [`is_clifford_rotation`]
    /// to check a specific rotation angle.
    pub fn is_clifford(&self) -> bool {
        matches!(
            self,
            Self::H | Self::X | Self::Y | Self::Z | Self::S | Self::Sdg
                | Self::Cx | Self::Cz | Self::Swap
        )
    }

    /// Whether this gate is a non-Clifford gate.
    ///
    /// T, Tdg, and CCX are always non-Clifford. Parametric gates (Rx, Ry, Rz)
    /// are considered non-Clifford by this method since their angle may be
    /// non-Clifford.
    pub fn is_non_clifford(&self) -> bool {
        !self.is_clifford()
    }
}

/// Check whether a rotation angle corresponds to a Clifford rotation.
///
/// A rotation Rz(θ) is Clifford when θ is a multiple of π/2
/// (i.e., the gate is equivalent to I, S, Z, or Sdg).
pub fn is_clifford_angle(theta: f64) -> bool {
    let half_pi = std::f64::consts::FRAC_PI_2;
    let ratio = theta / half_pi;
    (ratio - ratio.round()).abs() < 1e-10
}

/// Check whether a rotation angle is a T-gate multiple (π/4).
///
/// Returns true if θ is a multiple of π/4 — these can be exactly
/// decomposed into sequences of T and Clifford gates.
pub fn is_t_angle(theta: f64) -> bool {
    let quarter_pi = std::f64::consts::FRAC_PI_4;
    let ratio = theta / quarter_pi;
    (ratio - ratio.round()).abs() < 1e-10
}

impl std::fmt::Display for GateName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

// ── AST nodes ────────────────────────────────────────────────────────────────

/// A single gate application, e.g. `h q0` or `rx 1.57 q0`.
#[derive(Debug, Clone, PartialEq)]
pub struct Gate {
    pub name: GateName,
    pub qubits: Vec<usize>,
    pub params: Vec<f64>,
}

/// A measurement directive: `measure qN -> cN`.
#[derive(Debug, Clone, PartialEq)]
pub struct Measure {
    pub qubit: usize,
    pub cbit: usize,
}

/// A classically-conditioned gate: `if cN == M: gate qN`.
#[derive(Debug, Clone, PartialEq)]
pub struct ConditionalGate {
    pub cbit: usize,
    pub cbit_value: u32,
    pub gate: Gate,
}

/// An assertion hint (non-executable): `expect state "..."`.
#[derive(Debug, Clone, PartialEq)]
pub struct Expect {
    pub kind: ExpectKind,
    pub value: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ExpectKind {
    State,
    Counts,
    Relation,
}

/// A user-defined type alias: `type QubitPair = (Qubit, Qubit)`.
#[derive(Debug, Clone, PartialEq)]
pub struct TypeDecl {
    pub name: String,
    pub definition: String,
}

/// A gate inside a variational loop with symbolic parameters.
#[derive(Debug, Clone, PartialEq)]
pub struct VariationalGate {
    pub name: GateName,
    pub qubits: Vec<usize>,
    pub param_refs: Vec<String>,
}

/// A variational optimisation block (VQE/QAOA ansatz).
#[derive(Debug, Clone, PartialEq)]
pub struct VariationalLoop {
    pub params: Vec<String>,
    pub max_iter: u32,
    pub body: Vec<VariationalGate>,
}

/// Root AST node for a parsed Ehrenfest program.
#[derive(Debug, Clone, PartialEq)]
pub struct EhrenfestAst {
    pub name: String,
    pub n_qubits: usize,
    pub prepare: Option<String>,
    pub gates: Vec<Gate>,
    pub measures: Vec<Measure>,
    pub conditionals: Vec<ConditionalGate>,
    pub expects: Vec<Expect>,
    pub type_decls: Vec<TypeDecl>,
    pub variational_loops: Vec<VariationalLoop>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::f64::consts::{FRAC_PI_2, FRAC_PI_4, PI};

    fn all_gate_names() -> Vec<GateName> {
        vec![
            GateName::H,
            GateName::X,
            GateName::Y,
            GateName::Z,
            GateName::S,
            GateName::T,
            GateName::Sdg,
            GateName::Tdg,
            GateName::Cx,
            GateName::Cz,
            GateName::Swap,
            GateName::Ccx,
            GateName::Rx,
            GateName::Ry,
            GateName::Rz,
        ]
    }

    #[test]
    fn from_token_resolves_h() {
        assert_eq!(GateName::from_token("h"), Some(GateName::H));
    }

    #[test]
    fn from_token_resolves_x() {
        assert_eq!(GateName::from_token("x"), Some(GateName::X));
    }

    #[test]
    fn from_token_resolves_y() {
        assert_eq!(GateName::from_token("y"), Some(GateName::Y));
    }

    #[test]
    fn from_token_resolves_z() {
        assert_eq!(GateName::from_token("z"), Some(GateName::Z));
    }

    #[test]
    fn from_token_resolves_s() {
        assert_eq!(GateName::from_token("s"), Some(GateName::S));
    }

    #[test]
    fn from_token_resolves_t() {
        assert_eq!(GateName::from_token("t"), Some(GateName::T));
    }

    #[test]
    fn from_token_resolves_sdg() {
        assert_eq!(GateName::from_token("sdg"), Some(GateName::Sdg));
    }

    #[test]
    fn from_token_resolves_tdg() {
        assert_eq!(GateName::from_token("tdg"), Some(GateName::Tdg));
    }

    #[test]
    fn from_token_resolves_cx() {
        assert_eq!(GateName::from_token("cx"), Some(GateName::Cx));
    }

    #[test]
    fn from_token_resolves_cnot_alias_to_cx() {
        assert_eq!(GateName::from_token("cnot"), Some(GateName::Cx));
    }

    #[test]
    fn from_token_resolves_cz() {
        assert_eq!(GateName::from_token("cz"), Some(GateName::Cz));
    }

    #[test]
    fn from_token_resolves_swap() {
        assert_eq!(GateName::from_token("swap"), Some(GateName::Swap));
    }

    #[test]
    fn from_token_resolves_ccx() {
        assert_eq!(GateName::from_token("ccx"), Some(GateName::Ccx));
    }

    #[test]
    fn from_token_resolves_toffoli_alias_to_ccx() {
        assert_eq!(GateName::from_token("toffoli"), Some(GateName::Ccx));
    }

    #[test]
    fn from_token_resolves_rx() {
        assert_eq!(GateName::from_token("rx"), Some(GateName::Rx));
    }

    #[test]
    fn from_token_resolves_ry() {
        assert_eq!(GateName::from_token("ry"), Some(GateName::Ry));
    }

    #[test]
    fn from_token_resolves_rz() {
        assert_eq!(GateName::from_token("rz"), Some(GateName::Rz));
    }

    #[test]
    fn from_token_returns_none_for_unrecognised_token() {
        assert_eq!(GateName::from_token("unknown"), None);
        assert_eq!(GateName::from_token("CNOT"), None);
        assert_eq!(GateName::from_token(""), None);
    }

    #[test]
    fn as_str_returns_canonical_name_for_each_variant() {
        let cases = [
            (GateName::H, "h"),
            (GateName::X, "x"),
            (GateName::Y, "y"),
            (GateName::Z, "z"),
            (GateName::S, "s"),
            (GateName::T, "t"),
            (GateName::Sdg, "sdg"),
            (GateName::Tdg, "tdg"),
            (GateName::Cx, "cx"),
            (GateName::Cz, "cz"),
            (GateName::Swap, "swap"),
            (GateName::Ccx, "ccx"),
            (GateName::Rx, "rx"),
            (GateName::Ry, "ry"),
            (GateName::Rz, "rz"),
        ];
        for (gate, expected) in cases {
            assert_eq!(gate.as_str(), expected);
        }
    }

    #[test]
    fn from_token_round_trips_as_str_for_every_variant() {
        for gate in all_gate_names() {
            assert_eq!(GateName::from_token(gate.as_str()), Some(gate.clone()));
        }
    }

    #[test]
    fn arity_groups_single_qubit_gates() {
        let single = [
            GateName::H,
            GateName::X,
            GateName::Y,
            GateName::Z,
            GateName::S,
            GateName::T,
            GateName::Sdg,
            GateName::Tdg,
            GateName::Rx,
            GateName::Ry,
            GateName::Rz,
        ];
        for gate in single {
            assert_eq!(gate.arity(), 1, "expected {} to be single-qubit", gate);
        }
    }

    #[test]
    fn arity_groups_two_qubit_gates() {
        let two = [GateName::Cx, GateName::Cz, GateName::Swap];
        for gate in two {
            assert_eq!(gate.arity(), 2, "expected {} to be two-qubit", gate);
        }
    }

    #[test]
    fn arity_groups_three_qubit_gates() {
        assert_eq!(GateName::Ccx.arity(), 3);
    }

    #[test]
    fn is_parametric_is_true_only_for_rotation_gates() {
        assert!(GateName::Rx.is_parametric());
        assert!(GateName::Ry.is_parametric());
        assert!(GateName::Rz.is_parametric());
        for gate in all_gate_names() {
            if !matches!(gate, GateName::Rx | GateName::Ry | GateName::Rz) {
                assert!(
                    !gate.is_parametric(),
                    "expected {} to be non-parametric",
                    gate
                );
            }
        }
    }

    #[test]
    fn is_clifford_is_true_for_documented_clifford_gates() {
        let clifford = [
            GateName::H,
            GateName::X,
            GateName::Y,
            GateName::Z,
            GateName::S,
            GateName::Sdg,
            GateName::Cx,
            GateName::Cz,
            GateName::Swap,
        ];
        for gate in clifford {
            assert!(gate.is_clifford(), "expected {} to be Clifford", gate);
        }
    }

    #[test]
    fn is_clifford_is_false_for_non_clifford_gates() {
        let non_clifford = [
            GateName::T,
            GateName::Tdg,
            GateName::Ccx,
            GateName::Rx,
            GateName::Ry,
            GateName::Rz,
        ];
        for gate in non_clifford {
            assert!(!gate.is_clifford(), "expected {} not to be Clifford", gate);
        }
    }

    #[test]
    fn is_non_clifford_is_exact_negation_of_is_clifford_for_every_variant() {
        for gate in all_gate_names() {
            assert_eq!(
                gate.is_non_clifford(),
                !gate.is_clifford(),
                "negation mismatch for {}",
                gate
            );
        }
    }

    #[test]
    fn display_matches_as_str_for_every_variant() {
        for gate in all_gate_names() {
            assert_eq!(format!("{}", gate), gate.as_str());
        }
    }

    #[test]
    fn is_clifford_angle_accepts_multiples_of_half_pi() {
        assert!(is_clifford_angle(0.0));
        assert!(is_clifford_angle(FRAC_PI_2));
        assert!(is_clifford_angle(PI));
        assert!(is_clifford_angle(-FRAC_PI_2));
        assert!(is_clifford_angle(3.0 * FRAC_PI_2));
        assert!(is_clifford_angle(2.0 * PI));
    }

    #[test]
    fn is_clifford_angle_rejects_non_half_pi_multiples() {
        assert!(!is_clifford_angle(FRAC_PI_4));
        assert!(!is_clifford_angle(0.1));
        assert!(!is_clifford_angle(PI / 3.0));
    }

    #[test]
    fn is_t_angle_accepts_multiples_of_quarter_pi() {
        assert!(is_t_angle(0.0));
        assert!(is_t_angle(FRAC_PI_4));
        assert!(is_t_angle(FRAC_PI_2));
        assert!(is_t_angle(PI));
        assert!(is_t_angle(-FRAC_PI_4));
        assert!(is_t_angle(3.0 * FRAC_PI_4));
        assert!(is_t_angle(2.0 * PI));
    }

    #[test]
    fn is_t_angle_rejects_non_quarter_pi_multiples() {
        assert!(!is_t_angle(PI / 3.0));
        assert!(!is_t_angle(0.1));
        assert!(!is_t_angle(FRAC_PI_2 + 0.01));
    }
}
